name: 'AWS S3 sync w/ output'
description: 'Sync a directory to a S3 bucket'
branding:
  icon: box
  color: orange
inputs:
  directory:
    description: 'Directory to sync'
    required: false
    default: 'dist/'
  s3-bucket:
    description: 'S3 bucket to sync to'
    required: true
  args:
    description: 'Additional arguments for sync command'
    required: false
    default: ''
outputs:
  stdout:
    description: 'Output of AWS S3 sync'
    value: ${{ steps.sync.outputs.stdout }}
runs:
  using: "composite"
  steps:
    - id: sync
      run: OUTPUT=$(aws s3 sync ${{ inputs.directory }} s3://${{ inputs.s3-bucket }}/ ${{ inputs.args }}) && echo "::set-output name=stdout::$OUTPUT"
      shell: bash
